@extends('layout.body')

@section('title', 'Sejarah')
@section('header', 'Sejarah Singkat')

@section('content')
<!-- ======= Facts Section ======= -->
    <section class="facts pt-5">
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-8">
            <p>Perjalanan sejarah menjadi Paroki Maria Bunda Segala Bangsa (MBSB) dimulai saat umat Katolik di Kecamatan Gunung Putri, Cileungsi, Jonggol dan Cariu masih menjadi bagian dari Wilayah St. Yudas Tadeus yang merupakan salah satu wilayah dari Stasi St. Simon (Stasi Citeureup). Kemudian pada 5 Juli 1975 Stasi St. Philipus (bagian dari Paroki Katedral Bogor) diresmikan menjadi Paroki Keluarga Kudus, Cibinong oleh Uskup Bogor Mgr. N. Geise, OFM. Stasi St. Simon (Stasi Citeureup) menjadi bagian Paroki Keluarga Kudus. Kelahiran paroki yang disiapkan dan dibidani oleh Pastor GWJ. Ruijs, OFM. yang bertugas sebagai pastor paroki pertama sampai 1978. Dalam pelayanannya dibantu oleh Romo Felix Teguh Suwarno, Pr. Romo Benedictus Sudjarwo, Pr. Romo S. Suparman Pr. dan Romo A. Brotowiratmo, Pr. (hal 39-40, 25 tahun Paroki Keluarga Kudus Cibinong).</p><br />
            <p>Dari keberadaan dua orang guru yang beragama Katolik di Kecamatan Jonggol tahun 1976 perkembangan umat Katolik mulai terdata dan terorganisir. Pada 1 Mei 1977, Dinas Pendidikan propinsi Jawa Barat meminta guru-guru lulusan Sekolah Pendidikan Guru (SPG) propinsi Daerah Istimewa Yogyakarta sebanyak  5000  orang, untuk ditugaskan di propinsi daerah Jawa Barat dan disebar ke Kota Madya dan kecamatan. Kabupaten Bogor mendapat jatah sebanyak 762 orang, 45 orang diantaranya ditugaskan di kecamatan Jonggol.  Selanjutnya pada  14 Mei 1977, dilakukan pendataan guru yang beragama Katolik oleh Pastor GWJ. Ruijs OFM, ada  5 guru  di Kecamatan Jonggol; 4 guru di Kecamatan Cariu dan 8 guru di Kecamatan Cileungsi. Berdasarkan hasil pendataan yang dilakukan, terdapat 94  guru Inpres beragama Katolik di seluruh Kabupaten Bogor. Pernah diadakan perayaan ekaristi ditingkat kabupaten yang meliputi Kecamatan Cileungsi, Jonggol dan Cariu, perayaan ekaristi dilaksanakan di rumah Bapak Naaman Cian (tokoh agama Kristen).</p><br />
            <p>Perkembangan yang cukup pesat di Kecamatan Jonggol dan Cileungsi, yang tadinya bagian dari wilayah St. Yudas Tadeus, daerah Kecamatan Jonggol menjadi Stasi St. Arnoldus dan pada 26 November 1988 daerah Kecamatan Cileungsi dikukuhkan menjadi Stasi St. Yohanes Berchmans, Cileungsi.  Perayaan ekaristi diadakan dari rumah ke rumah setiap dua minggu sekali oleh Pastor Diaz Viera, SVD.</p><br />
            <p>Pengurus Stasi St. Yohanes Berchmans periode I (1988-1991) dibentuk dan diketuai oleh Bapak Paulus Sutiman, pelayanan umat stasi dipusatkan di rumah Bapak Paulus Sutiman, Perumahan PT. Semen Cibinong (red. Semen Holcim saat ini). Beliau menjabat kembali periode II (1991-1994), dengan jumlah 41 KK yang tersebar dalam 3 lingkungan (St. Fransiskus, St. Anna dan St. Petrus). Perayaan ekaristi dilaksanakan dua kali dalam sebulan bergantian oleh Romo Franz Lorry, Pr. dan Romo Christoforus Lamen Sani, Pr. Minggu I di rumah ketua stasi dan Minggu III di rumah umat secara bergantian. Pada periode II ini terbentuk Mudika Stasi diketuai oleh FX. Sudiman dan PPMK (Persatuan Pemuda Mahasiswa Katolik) yang diketuai oleh Sdr. Suidi, WKRI yang diketuai oleh Ibu Paulus Sutiman. Tahun 1994 umat stasi mencapai 100 KK, beberapa kendala yang dihadapi oleh kepengurusan Periode I dan II, adanya intimidasi dan larangan mengadakan perayaan ekaristi di rumah Bapak Paulus Sutiman, lahan fasos di Kenari untuk Gereja Katolik yang sudah mulai tiang pancang dihancurkan oleh orang yang tidak menghendaki kehadiran gereja di wilayah ini.</p><br />
            <p>Namun Tuhan Yesus tidak berdiam diri, pada 4 November 1997 Uskup Bogor Mgr. Michael Cosmas Angkur, OFM. Secara resmi menerima Tarekat Suster-suster Putri Bunda Hati Kudus (PBHK) yang berkarya di wilayah Paroki Keluarga Kudus Cibinong, tepatnya di Kota Wisata, Cibubur, Cileungsi. Sejak Juni 1998 PBHK yang mendiami rumah di Pesona Paris C4 No. 50-51, Kota Wisata hadir di tengah umat menjadi bagian dari stasi Yohanes Berchmans Cileungsi, menjadi motor penggerak perkembangan menuju paroki dan rumah susteran ini menjadi tempat perayaan ekaristi setiap Jumat pukul 18:00 WIB. Umat berkembang dan akhirnya dibentuk lingkungan BHK yang diketuai oleh Bapak Yohanes B. Elmud.</p><br />
            <img src="/src/img/sejarah/sejarah1.jpg" class="mb-5" width="100%">
            <p>Periode stasi berlanjut, Periode III (1994-1998) diketuai oleh Bapak Heribertus Kasijan, perayaan ekaristi dua kali sebulan Minggu I di rumah Bapak Martinus Whan Gunarto atau Bapak S. Sugiyono dan Minggu III secara bergilir dari rumah ke rumah. Stasi juga mendapat tugas tatib dan koor di Paroki Keluarga Kudus, Cibinong satu bulan satu kali.  Perkembangan umat 155 KK tahun 1996 menjadi 200 KK tahun 1998 terbagi dalam 6 lingkungan (St. Fransiskus, St. Anna, St. Petrus, Ratu Pecinta Damai, Maria Bunda Karmel dan Bunda Hati Kudus). Periode III berakhir dengan beberapa kendala,  tempat beribadah yang bisa menampung seluruh umat, adanya surat edaran rumah bukan tempat ibadah, adanya larangan mengadakan Natalan di wilayah Kenari, adanya larangan WKRI mengadakan bazar. Lingkungan BHK diketuai oleh Bapak Benedictus Susanto.</p><br />
            <p>Periode IV (1998-2001) diketuai oleh Bapak Yusuf Harsoyo, perayaan ekaristi yang semula dari rumah ke rumah pada Minggu I dan III, pada 3 Februari 2000 terjadi kesepakatan dengan PBHK disetujui  Sr. Maria Regina Pratiwi PBHK mewakili Yayasan Asti Dharma untuk bisa memakai selasar sekolah BHK menjadi tempat perayaan ekaristi setiap Minggu pukul 11:00 WIB, saat itu Pastor Paroki Keluarga Kudus Cibinong adalah Romo Agustinus Adi Indiantono, Pr. Selanjutnya stasi dilayani oleh Romo Michael Suharsono, Pr. Yang dilantik menjadi Pastor Paroki Keluarga Kudus Cibinong ke-8 pada 1 Juli 2000.</p> <br />
            <img src="/src/img/sejarah/sejarah2.jpg" class="mb-5" width="100%">
            <p>Perayaan ekaristi masih setiap Minggu pukul 11.00 WIB dengan jumlah umat berkisar  200 - 300 jiwa setiap perayaan ekaristi. Pada periode stasi ini PBHK mendapat komitmen dari Pengembang Kota Wisata bahwa Gereja Katolik mendapat hak penggunaan tanah seluas kurang lebih 6000 m2 untuk gereja Katolik. Tahun 2000 tersebut juga terbentuk Panitia Pembangunan Gereja (PPG) untuk mempersiapkan sarana dan prasarana tempat ibadat di dalam komplek Kota Wisata. Atas jerih payah PPG yang dipimpin Bapak Laurentius Dwi Anggodo selama dua generasi dan doa seluruh umat, PPG mendapat Ijin Mendirikan Bangunan (IMB) untuk mendirikan tiga bangunan: gereja, pastoran dan gedung meditasi (gedung serba guna). Saat ini di tanah fasum tersebut sudah berdiri 3 bangunan: gereja, pastoran dan gedung serba guna.</p><br />
            <p>Terjadi stagnasi kepengurusan, maka Pastor Paroki berdasarkan SK-DPP-KKC No.06/DP/PKKC/I/02 tertanggal 20 Januari 2002, membentuk formatur 20 Januari-9 Mei 2002, diketuai oleh Stevanus Sembiring yang bertugas merencanakan dan melaksanakan pemilihan Ketua Stasi baru dan mengatur kehidupan umat sampai diangkatnya Ketua Stasi baru.</p><br />
            <p>Periode V stasi (2002-2005) diketuai oleh Bapak Paulus Herianto, dilantik pada Perayaan ekaristi stasi bertepatan dengan Hari Raya Kenaikan Tuhan di SD BHK Kota Wisata oleh Romo Michael Suharsono, Pr. Dilanjutkan dengan acara serah terima dan ramah tamah di Aula TK BHK antara pengurus stasi lama, pengurus stasi transisi dan pengurus stasi baru. Kepengurusan diawali dengan Raker Stasi pada tanggal 16 Juli 2002, untuk menyusun program kerja dan anggaran satu tahun kedepan di Wisma Samadi Klender. Pada akhir Oktober 2003 umat stasi St. Yohanes Berchman tercatat 918 KK yang tersebar dalam 4 Wilayah 19 Lingkungan. Dilayani  bergantian oleh Romo Michael Suharsono, Pr., Antonius Dwi Haryanto, Pr. dan Ignatius Besembun, Pr.</p><br />
            <img src="/src/img/sejarah/sejarah3.jpg" class="mb-5" width="100%">
            <p>Pada tahun 2004 pembangunan gereja dimulai dengan diawali peletakan batu pertama pembangunan gereja oleh Uskup Bogor Mgr. Michael Cosmas Angkur OFM  pada 14 Desember 2003 didampingi duta besar Vatikan dan Purnomo Yusgiantoro. Tahun 2004 selain berkat dimulainya pembangunan gedung gereja, juga dampak psikologi dari Sekolah Sang Timur, Ciledug, memaksa kita memindahkan perayaan ekaristi dari selasar sekolah BHK ke areal gereja yang belum layak pakai, dimulai sejak perayaan ekaristi perdana pada 10 Oktober 2004.</p><br />
            <img src="/src/img/sejarah/sejarah4.jpg" class="mb-5" width="100%">
            <p>Setiap minggu pengurus dan umat memasang tenda darurat di dalam bangunan gereja sebab atap belum ada dan berlantaikan tanah tanpa keramik. Setiap perayaan ekaristi terasa memprihatinkan, kepanasan dan jika hujan  umat  basah kuyup dan kena lumpur. Tapi, anehnya itu bisa terjadi juga di pemukiman perumahan Kota Wisata. Dan justru situasi ini membawa banyak berkat bagi gereja, karena mulai saat itu justru pertambahan umat yang hadir dalam perayaan ekaristi bertambah begitu pesat. Meski bangku atau tempat duduk gereja yang disediakan kurang lebih sebanyak 1500 kursi plastik,  umat yang berada di luar gereja juga masih cukup banyak dan sebagian tidak dapat tempat duduk setiap perayaan ekaristi.</p><br />
            <p>Kerinduan umat untuk mempunyai pastor di gereja Kota Wisata, Uskup Bogor Mgr. Michael Cosmas Angkur OFM meningkatkan stasus Stasi  St. Yohanes Berchmans, efektif  21Juli 2004, melalui SK Uskup Nomor 15/SKB/VII/2004 menjadi Paroki Persiapan Cileungsi. Dari Juli 2004 sampai awal 2005, peralihan dan pembentukan pengurus baru Dewan Pastoral Paroki Persiapan Cileungsi (DPPP-C) yang dipimpin oleh Pastor Paroki Keluarga Kudus, Cibinong, Romo Michael Suharsono, Pr. dan Wakil Ketua Bapak Silvester Agustinus Supardi menggantikan Ketua Stasi St. Yohanes Berchmans yaitu Bapak Paulus Herianto.</p><br />
            <img src="/src/img/sejarah/sejarah5.jpg" class="mb-5" width="100%">
            <p>Paroki Persiapan Cileungsi mendapat tanggung jawab membawahi dua stasi, yaitu stasi St. Arnoldus, Jonggol, yang sebelumnya adalah stasi dari Paroki Keluarga Kudus, Cibinong dan St. Maria Mediatrix, yang pada Agustus 2003 bergabung ke Paroki Keluarga Kudus, Cibinong dari Paroki St. Bartolomeus, Taman Galaksi, Keuskupan Agung Jakarta.  Setelah bergabung dengan Paroki Keluarga Kudus Cibinong misa Minggu II dan Minggu IV pukul 16:00 WIB. Lingkungan Vincentius yang semula bagian dari Paroki St. Servatius Kampung Sawah bergabung ke Paroki Persiapan Cileungsi pada 2004.</p><br />
            <p>Paroki Persiapan Cileungsi adalah paroki yang unik, sebagian besar umat adalah keluarga muda dengan dua atau tiga anak kecil dan umat dengan berbagai latar belakang dan budaya paroki dan keuskupan. Ide, gagasan, wacana, dinamika berlingkungan, berparoki dan banyaknya anak kecil, menjadi kekayaan tersendiri di Paroki Persiapan Cileungsi ini.</p><br />
            <p>Pada saat itu perayaan ekaristi rutin  setiap Jumat sore di susteran PBHK, Kamis sore di susteran KFS Jonggol,  sebulan sekali, Sabtu sore pukul 18.00 WIB dan Minggu pukul 08.00 WIB perayaan ekaristi di gereja kemudian ditambah perayaan ekaristi pada Minggu sore. Sementara pelayanan sakramen, pelayanan baptis anak-anak sekolah dan dewasa, seperti biasa setiap jelang perayaan Natal dan Paskah. Sedangkan baptis bayi setiap bulan dengan rata-rata 15 – 20 anak. Pelayanan sakramen Krisma dua tahun sekali. Komuni Pertama  setahun sekali. Pelayanan sakramen Tobat setiap menjelang perayaan Natal dan Paskah. Pelayanan Sakramen Perkawinan dan Perminyakan Orang Sakit sesuai kebutuhan.</p><br />
            <img src="/src/img/sejarah/sejarah6.jpg" class="mb-5" width="100%">
            <p>Untuk kegiatan kelompok, putra-putri mulai dari tingkat SD, SMP, dan SMA yang kebetulan bersekolah non Katolik, paroki juga memberikan pelajaran agama.</p><br />
            <p>Persekutuan Doa Katolik Karismatik (PDKK) St. Yohanes Berchmans dan Kelompok Doa (KD) St. Philomena seminggu sekali dengan satu kali perayaan ekaristi setiap bulannya. Kelompok Petugas Liturgi, ada yang tugas setiap minggu atau dua minggu sekali, yaitu untuk koor, misdinar, lektor / lektris dan prodiakon. Kegiatan wilayah dan lingkungan, pembenahan Kartu Keluarga Katolik (K3) terus berjalan, di samping pembenahan dan pemekaran lingkungan. Paroki Persiapan Cileungsi terdiri dari 5 wilayah dan 20 lingkungan, stasi St. Arnoldus Jonggol terdiri dari 4 lingkungan dan stasi Sta. Maria Mediatrix terdiri dari 5 wilayah dan 15 lingkungan.</p><br />
            <p>Adapun para pelayan perayaan ekaristi adalah romo-romo dari Paroki Keluarga Kudus, Cibinong, seperti, RD Polycarpus Suyut, RD Dominikus Savio Tukiyo, RD Ignatius Besembun RD, Robertus Eeng Gunawan, RD  Antonius Dwi Haryanto, RD Michael Suharsono, dan ditambah dari Keusukupan Bogor yakni RD Markus Lukas, RD FX Suyono, RD Markus Santoso  dan RD Stanislaus Pujiantoro. </p><br />
            <p>Sebagai catatan sejarah beberapa gembala yang pernah membina Stasi St. Yohanes Berchmans adalah Pastor EJ. Rijper, OFM. Pastor Diaz Viera, SVD. Romo Franz Lorry, RD Agustinus Adi Indiantono, Romo Christoforus Lamen Sani, Pr. RD B. Sudjarwo,  RD Parman, RD Felix Teguh Suwarno, RD Yohanes Hardono, dan romo-romo lainnya.</p><br />
            <p>Beberapa pencapaian dan catatan penting dalam masa Dewan Pastoral Paroki Persiapan Cileungsi (DPPP-Cileungsi) Periode 2005-2008 (SK Uskup Nomor 15/SKB/VII/2004, Stasi St. Yohanes Berchmans  menjadi Paroki Persiapan Cileungsi, yang berlaku efektif 21 Juli 2004).</p><br />
            <p>Januari 2006, pembentukan tim kecil untuk pengadaan Bangku Kita, dan pada Natal 2006 bangku gereja sudah dipakai. Maret 2006, KEP (Kursus Evangelisasi Pribadi) perdana dimulai oleh PDKK Yohanes Berchmans. 17 Februari 2008, Peletakan Batu pertama sebagai tanda dimulainya pembangunan pastoran oleh PPG III yang dipimpin oleh Bapak Josef Partono dan pastoran selesai Desember 2008. Paroki Persiapan Cileungsi, di perpanjang untuk menerima mandat Uskup Bogor Mgr. Michael Cosmas Angkur, OFM. menjadi tuan rumah Tahbisan 1  Imam dan 3 Diakon.</p><br />
            <p>Baru pada Selasa, 20 Mei 2008 disaat menjadi tuan Rumah Tahbisan 1 Imam dan 3 Diakon, pada saat Homili Uskup Bogor Mgr. Cosmas Angkur, OFM. secara lisan mengumumkan Paroki Persiapan menjadi Paroki Maria Bunda Segala Bangsa dan akan mendapat satu Pastor Paroki dan selanjutnya tanggal 20 Mei ini diputuskan menjadi hari ulang tahun Paroki. Melihat kedekatan geografis Stasi St. Arnoldus, Jonggol dan stasi St. Maria Mediatrix, tetap menjadi stasi di bawah reksa pastoral Paroki Maria Bunda Segala Bangsa.</p><br />
            <p><b>Per Juli 2019, Stasi St. Arnoldus, Jonggol telah diresmikan menjadi Paroki Hati Kudus Yesus.</b></p><br/>
            <p>Saat ini Paroki Maria Bunda Segala Bangsa digembalakan oleh RD. Bonifasius Heribertus Beke.</p><br />
            <p>Sumber:</p>
            <ul>
                <li>Buku Sejarah Perkembangan Stasi Yohanes Berchmans</li>
                <li>25 Tahun Paroki Keluarga Kudus Cibinong oleh DPP Keluarga Kudus</li>
                <li>Dokumen-dokumen stasi dan paroki</li>
            </ul>
          </div>
          <div class="col-lg-4 col-md-4">
            <!-- filler -->
          </div>
        </div>
      </div>
    </section><!-- End Facts Section -->
@endsection